name: Rebuild Site

on:
  push:
    branches: [ "main" ]

jobs:
  rebuild-site:

    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Generate Site
      run: dotnet run --project MahjongDkStats.CLI
    - uses: stefanzweifel/git-auto-commit-action@v5
    
